name: security-action
on:
  push:
    branches: [veracode-actions]
jobs:
  veracode-auto-package:
    name: veracode auto-package
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: veracode CLI Download
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: |        
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output . --trust
          ls -l | grep veracode-auto-pack-go-dvwa-go.zip

      - name: salvando artefato
        uses: actions/upload-artifact@v4
        with:
            name: veracode_pack
            path: ./veracode-auto-pack-go-dvwa-go.zip

  veracode-sast-pipeline-scan:
    runs-on: ubuntu-latest
    needs: [ veracode-auto-package ]
    name: veracode sast pipeline scan

    steps:
      - name: get archive
        uses: actions/download-artifact@v4 
        with:
          name: veracode_pack
          path: .

      - name: pipeline-scan action step
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.16
        with:
          vid: ${{ secrets.VERACODE_ID }}
          vkey: ${{ secrets.VERACODE_KEY }}
          file: "veracode-auto-pack-go-dvwa-go.zip"
          fail_build: "false"